version: '3.1'
services:
  dbPostgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=gestionarticle
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - db:/var/lib/postgres
  dbMysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: gestionarticle
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
