version: '3.1'
services:
  server:
    container_name: gestionarticle:latest
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - 80:8080

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'gestionarticle'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: null