version: '3.1'
services:
  server:
    container_name: gestionarticle
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - app-network

  db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE handle error silently
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER: root
      - MYSQL_PASSWORD: root
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: jdbc:mysql://localhost/gestionarticle
      - MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306

networks:
  app-network:
    driver: bridge