version: '3.3'
services:
  server:
    image: chatbrume/gestion-article
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    network_mode: 'host'

  db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE handle error silently
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - 3306:3306