---
- name: playbook
  hosts: local_web_server_1
  become: yes
  vars_files:
    - database_info.yml
  environment:
    MYSQL_USER: '{{MYSQL_USER}}'
    MYSQL_PASSWORD: '{{MYSQL_PASSWORD}}'
    MYSQL_DATABASE: '{{MYSQL_DATABASE}}'
    MYSQL_ALLOW_EMPTY_PASSWORD: '{{ MYSQL_ALLOW_EMPTY_PASSWORD }}'

  pre_tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        [
            "apt-transport-https",
            "ca-certificates",
            "curl",
            "software-properties-common",
#            "python-pip",
            "python3-pip",
            "python-apt",
            "virtualenv",
            "python-setuptools",
            "net-tools"
        ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce and docker-compose
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ "docker-ce","docker-compose" ]

#    - name: Update apt and install docker-ce
#      apt: name={{ item }} state=latest update_cache=yes
#      loop: ["docker-ce"]

#    - name: Install Python Docker Module
#      pip:
#        name: docker

    - name: Install Docker Module for Python
      pip:
        name: docker

  tasks:
    - name: git clone project
      git:
        repo: https://github.com/Chatbrume/GestionArticle.git
        dest: /home/GestionArticle


    - name: run docker-compose
      community.docker.docker_compose:
        project_src: /home/GestionArticle

